### ISSUE TITLE
Symlinks

### ISSUE THREAD

**Issue by cescoferraro** [60frames/webpack-hot-server-middleware#14] opened 2017-02-22 09:38 UTC
I am having an issue with https://github.com/supasate/connected-react-router and started debugging.
I did `yarn link` and `yarn link connected-react-router`, and now the middleware cannot see the symlink as a regular folder.

**Comment by richardscarrott** [comment] 2017-02-22 22:23
@cescoferraro I just tried with `npm link` and it worked fine, only extra step I had to take was to run `npm run build` within the 'connected-react-router' repo to ensure it builds 'lib/index.js'.

If you're still having issues could you push up a reduced test case for me to investigate?

**Comment by cescoferraro** [comment] 2017-02-22 23:05
That might be it. Will give it a go

**Comment by cescoferraro** [comment] 2017-03-03 14:49
I tried this again when messing with [d3act](https://github.com/AnSavvides/d3act).
Still no luck, ran npm start/build. And the files still do not show.
Maybe these is related to the fact that I am running webpack-hot-server-middleware inside a docker container. Will look further into these.

**Comment by richardscarrott** [comment] 2017-04-18 12:59
@cescoferraro is this still an issue for you?

**Comment by richardscarrott** [comment] 2017-05-05 17:56
@cescoferraro I'm going to close this as I've been unable to reproduce the same problem. If you can provide further details I can reinvestigate.

**Closed by richardscarrott** 2017-05-05 17:56 UTC
